/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.information.system;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MWK
 */
public class Admin_loOgo extends javax.swing.JFrame {

    /**
     * Creates new form Admin_loOgo
     */
    public Admin_loOgo() {
        initComponents();
        this.setSize(400,360);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        level1 = new javax.swing.JRadioButton();
        level2 = new javax.swing.JRadioButton();
        level3 = new javax.swing.JRadioButton();
        level4 = new javax.swing.JRadioButton();
        levels = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        print = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        log_out = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        level1.setBackground(new java.awt.Color(0, 0, 51));
        buttonGroup1.add(level1);
        level1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        level1.setForeground(new java.awt.Color(255, 255, 255));
        level1.setText("  Level  1");
        getContentPane().add(level1);
        level1.setBounds(140, 47, 140, 27);

        level2.setBackground(new java.awt.Color(0, 0, 51));
        buttonGroup1.add(level2);
        level2.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        level2.setForeground(new java.awt.Color(255, 255, 255));
        level2.setText("  Level  2");
        getContentPane().add(level2);
        level2.setBounds(140, 92, 180, 27);

        level3.setBackground(new java.awt.Color(0, 0, 51));
        buttonGroup1.add(level3);
        level3.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        level3.setForeground(new java.awt.Color(255, 255, 255));
        level3.setText("  Level  3");
        getContentPane().add(level3);
        level3.setBounds(140, 137, 160, 27);

        level4.setBackground(new java.awt.Color(0, 0, 51));
        buttonGroup1.add(level4);
        level4.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        level4.setForeground(new java.awt.Color(255, 255, 255));
        level4.setText("  Level  4");
        getContentPane().add(level4);
        level4.setBounds(140, 182, 160, 27);

        levels.setBackground(new java.awt.Color(0, 0, 51));
        buttonGroup1.add(levels);
        levels.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        levels.setForeground(new java.awt.Color(255, 255, 255));
        levels.setText("  All Levels");
        getContentPane().add(levels);
        levels.setBounds(140, 230, 160, 27);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        print.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        print.setForeground(new java.awt.Color(0, 0, 102));
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 140, -1));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Update DeadLine");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 280, 150, -1));

        log_out.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        log_out.setForeground(new java.awt.Color(0, 0, 102));
        log_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/information/system/images/icons24x24/iconfinder_Exit_132530.png"))); // NOI18N
        log_out.setText("Log out");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        jPanel1.add(log_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 10, 110, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        if(level1.isSelected())
        {
            AllStudent std= new AllStudent();
            std.setLevel(1);
            std.setVisible(true);
            setVisible(false);
        }
        else if(level2.isSelected())
        {
            AllStudent std= new AllStudent();
            std.setLevel(2);
            std.setVisible(true);
            setVisible(false);
        }
        else if(level3.isSelected())
        {
            AllStudent std= new AllStudent();
            std.setLevel(3);
            std.setVisible(true);
            setVisible(false);
        }
        else if(level4.isSelected())
        {
            AllStudent std= new AllStudent();
            std.setLevel(4);
            std.setVisible(true);
            setVisible(false);
        }
        else if (levels.isSelected())
        {
             AllStudent std= new AllStudent();
            std.setLevel(0);
            std.setVisible(true);
            setVisible(false);
        }
        else
        {
             JOptionPane.showMessageDialog(null, " No Item Selected ", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_printActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        deadline n = new deadline();
n.setVisible(true);
setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        // TODO add your handling code here:
         the_login v= new the_login();
        v.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_log_outActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_loOgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_loOgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_loOgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_loOgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_loOgo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton level1;
    private javax.swing.JRadioButton level2;
    private javax.swing.JRadioButton level3;
    private javax.swing.JRadioButton level4;
    private javax.swing.JRadioButton levels;
    private javax.swing.JButton log_out;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
