/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.information.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MWK
 */
public class modifiy extends javax.swing.JFrame {

    /**
     * Creates new form modifiy
     */
    String user;
    Date DeadLine;    
    public modifiy() {
        initComponents();
        this.setSize(295,366);
        this.setTitle(" Modify Information ");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }
    
    public void setUP(String username)
    {
         user=username;
          try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url ="jdbc:sqlserver://localhost:1433;databaseName=test;user=sa;password=01098581649rod";
            Connection con =DriverManager.getConnection(url);
            String query="SELECT * FROM stdinfo where username = '"+user+"'";        
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            STDinfo s;
            if(rs.next())
            {
                 s=new STDinfo(rs.getInt("id"),rs.getString("name"),rs.getInt("stdlevel"),rs.getString("gendar"),rs.getDouble("gpa"),"",rs.getInt("stdhours"),"");   
                 
                 name.setText(s.getName());
            }
            String query2="SELECT * FROM date ";
            Statement st2 = con.createStatement();
            ResultSet rs2 = st2.executeQuery(query2);
            Dates d;
            if(rs2.next()){
                d=new Dates(rs2.getDate("deadline"));
                DeadLine=d.getDate();
                date.setText(DeadLine.toLocaleString());
            }
            
         }
        catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        modify = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modify.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        modify.setForeground(new java.awt.Color(0, 0, 51));
        modify.setText("Modify Courses ");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });
        jPanel1.add(modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 150, -1));

        print.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        print.setForeground(new java.awt.Color(0, 0, 51));
        print.setText("Print Information");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 150, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("      Welcome");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 260, 50));

        name.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 200, 30));

        logOut.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        logOut.setForeground(new java.awt.Color(0, 0, 51));
        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/information/system/images/icons24x24/iconfinder_Exit_132530.png"))); // NOI18N
        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jPanel1.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 150, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DeadLine  To Modify The Courses :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 210, 30));

        date.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 130, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/information/system/images/3d-male-hand-muscles-connected-dots-low-poly-wireframe-polygonal-athlete-body_47649-530.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url ="jdbc:sqlserver://localhost:1433;databaseName=test;user=sa;password=01098581649rod";
            Connection con =DriverManager.getConnection(url);
            String query="SELECT date0 FROM stdinfo where username = '"+user+"'";         
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            STDinfo s;
            if(rs.next())
            {
                 s=new STDinfo(0,"",0,"",0,"",0,rs.getObject("date0"));
                 Date str= (Date)s.getDate();
                 int t=DeadLine.compareTo(str);
                 if(t>0){    
                   //  JOptionPane.showMessageDialog(null,str.toLocaleString()+"  t="+t);                     
                    ModifyCourses i = new ModifyCourses();
                    i.setUP(user);
                    i.setVisible(true);
                     setVisible(false);
                 }
                 else 
                     JOptionPane.showMessageDialog(null, "The Date of Modifying Courses is Over");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_modifyActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
    
 print view =new print();
        view.setUP(user);
        view.setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        the_login v= new the_login();
        v.setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifiy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifiy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifiy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifiy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifiy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOut;
    private javax.swing.JButton modify;
    private javax.swing.JLabel name;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
