/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.information.system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MWK
 */
public class register_login extends javax.swing.JFrame {

    /**
     * Creates new form register_login
     */
    public register_login() {
        initComponents();
        this.setTitle(" Registreation ");
        this.setSize(401,400);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        confirmpassword = new javax.swing.JPasswordField();
        clearbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emptyuser = new javax.swing.JLabel();
        emptypassword = new javax.swing.JLabel();
        emptyconfirmpassword = new javax.swing.JLabel();
        phone_check = new javax.swing.JLabel();
        wrongemail = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameKeyReleased(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 168, 20));

        confirmpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmpasswordKeyReleased(evt);
            }
        });
        jPanel1.add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 168, -1));

        clearbtn.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(255, 0, 0));
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 108, -1));

        savebtn.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        savebtn.setForeground(new java.awt.Color(0, 0, 102));
        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/information/system/images/icons 16x16/iconfinder_OK_132710.png"))); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        jPanel1.add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 106, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 168, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username          ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password            ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-Mail           ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  Phone     ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, -1));

        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 168, -1));

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 168, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sign UP");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 22, -1, -1));

        emptyuser.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        emptyuser.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(emptyuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 170, 20));

        emptypassword.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        emptypassword.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(emptypassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 150, 20));

        emptyconfirmpassword.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        emptyconfirmpassword.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(emptyconfirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 170, 20));

        phone_check.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        phone_check.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(phone_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 170, 20));

        wrongemail.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        wrongemail.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(wrongemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 160, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/information/system/images/abstract-polygonal-running-legs-from-lines-triangles-and-particle-low-poly-wireframe-vector-illustration.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, 0, 730, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
    
                    username.setText("");
                    password.setText("");
                    email.setText("");
                    phone.setText("");
                    confirmpassword.setText("");           // TODO add your handling code here:
    }//GEN-LAST:event_clearbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
       
        if(username.getText().trim().isEmpty() &&password.getText().trim().isEmpty() && confirmpassword.getText().trim().isEmpty() && email.getText().trim().isEmpty() && phone.getText().trim().isEmpty())
        {
            emptyuser.setText("Username is Empty");
            emptypassword.setText("Password is Empty");
            emptyconfirmpassword.setText("Confirm Password is Empty");
            //emptyemail.setText("Email is Empty");
            //emptyphone.setText("Phone is Empty");
            
        }
       else if(username.getText().trim().isEmpty() &&password.getText().trim().isEmpty()){
           emptyuser.setText("Username is Empty");
            emptypassword.setText("Password is Empty");
       }
       else if(confirmpassword.getText().trim().isEmpty() &&password.getText().trim().isEmpty()){
           emptyconfirmpassword.setText("Confirm Password is Empty");
            emptypassword.setText("Password is Empty");
       }
       else if(username.getText().trim().isEmpty() ){
           emptyuser.setText("Username is Empty");
       }
       else if(password.getText().trim().isEmpty()){
            emptypassword.setText("Password is Empty");
       }
       else if (!email.getText().trim().isEmpty() && !(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email.getText())))
           wrongemail.setText("Invalid E-Mail");
       else if(!phone.getText().trim().isEmpty() && p()){
           phone_check.setText(" Invalid number ");
       }
       else     
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url ="jdbc:sqlserver://localhost:1433;databaseName=test;user=sa;password=01098581649rod";
            Connection con =DriverManager.getConnection(url);
            String sql="Select * from login0 where username=? ";
            PreparedStatement pst1=con.prepareStatement(sql);
            pst1.setString(1,username.getText());          
            ResultSet rs=pst1.executeQuery();            
            String query="insert into login0 (username,password,confirmpassword,email,phone)values(?,?,?,?,?);";
            PreparedStatement pst=con.prepareStatement(query);   
            String sr =password.getText();           
            String sr1 =confirmpassword.getText();           
            int result = sr.compareToIgnoreCase(sr1);
            if(!rs.next()){            
                if(result==0){
                    JOptionPane.showMessageDialog(null,"Successfully Registered");
                    pst.setString(1,username.getText());
                    pst.setString(2,password.getText());
                    pst.setString(3,confirmpassword.getText());                   
                    pst.setString(4,email.getText());
                    pst.setString(5,phone.getText());
                    pst.executeUpdate();
                    the_login view=new the_login();
                    view.setVisible(true);
                    setVisible(false);
                }
               else {
                        JOptionPane.showMessageDialog(null,"The Password isn't Matched ");                                       
                        password.setText("");
                        confirmpassword.setText("");
                    }
            }
          else {
                JOptionPane.showMessageDialog(null,"This Username is Selected");
                    username.setText("");
            }
        }
        
        catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
        }
         
    }//GEN-LAST:event_savebtnActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyReleased
    emptyuser.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_usernameKeyReleased

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
     emptypassword.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_passwordKeyReleased

    private void confirmpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmpasswordKeyReleased
         emptyconfirmpassword.setText("");        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpasswordKeyReleased

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed
       /* try{
            int phone_number = Integer.parseInt(phone.getText());
            phone_check.setText("");
        }
        catch(NumberFormatException e){
            phone_check.setText(" Invalid number ");
        }
       */
    }//GEN-LAST:event_phoneKeyPressed
    private boolean p(){
        try{
            int phone_number = Integer.parseInt(phone.getText().trim().toString());
            return false;
        }
        catch(NumberFormatException e){
            return true;
        }
    }
    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        wrongemail.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_emailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emptyconfirmpassword;
    private javax.swing.JLabel emptypassword;
    private javax.swing.JLabel emptyuser;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phone_check;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField username;
    private javax.swing.JLabel wrongemail;
    // End of variables declaration//GEN-END:variables

}
