/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.information.system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MWK
 */
public class S_I_S_login extends javax.swing.JFrame {

    /**
     * Creates new form S_I_S_login
     */
    public S_I_S_login() {
        initComponents();
        this.setTitle(" Student Information ");
        this.setSize(340,390);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        buttonGroup1.add(male);
        buttonGroup1.add(female);
                
    }

    String user;
    public void setUP(String username)
    {
         user=username;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        level = new javax.swing.JTextField();
        gpa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        emptyname = new javax.swing.JLabel();
        emptylevel = new javax.swing.JLabel();
        emptygpa = new javax.swing.JLabel();
        emptygendar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        save.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        save.setForeground(new java.awt.Color(0, 51, 102));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/information/system/images/icons 16x16/iconfinder_OK_132710.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 102, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name   :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Level   :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 72, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GPA     :   ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 72, -1));

        name.setForeground(new java.awt.Color(0, 0, 153));
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 168, -1));

        level.setForeground(new java.awt.Color(0, 0, 204));
        level.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                levelKeyReleased(evt);
            }
        });
        jPanel1.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 168, -1));

        gpa.setForeground(new java.awt.Color(0, 0, 153));
        gpa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gpaKeyReleased(evt);
            }
        });
        jPanel1.add(gpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 168, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        male.setBackground(new java.awt.Color(0, 102, 153));
        male.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("   Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        male.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maleKeyReleased(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        female.setBackground(new java.awt.Color(0, 102, 153));
        female.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("    Female");
        female.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                femaleKeyReleased(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        emptyname.setFont(new java.awt.Font("Trebuchet MS", 3, 10)); // NOI18N
        emptyname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(emptyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 160, 20));

        emptylevel.setFont(new java.awt.Font("Trebuchet MS", 3, 10)); // NOI18N
        emptylevel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(emptylevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 150, 20));

        emptygpa.setFont(new java.awt.Font("Trebuchet MS", 3, 10)); // NOI18N
        emptygpa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(emptygpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 150, 20));

        emptygendar.setFont(new java.awt.Font("Trebuchet MS", 3, 10)); // NOI18N
        emptygendar.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(emptygendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 160, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/information/system/images/abstract-plexus-background-with-connected-lines-dots-plexus-geometric-effect-big-data-complex-with-compounds-lines-plexus-minimal-array-digital-data-visualization_43969-954.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 560, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
            String gendar="";

        if(name.getText().trim().isEmpty() && level.getText().trim().isEmpty()&& gpa.getText().trim().isEmpty() &&!(male.isSelected()) &&!(female.isSelected()) )
        {
            emptyname.setText("Name is Empty");
            emptylevel.setText("Level is Empty");
            emptygendar.setText("Gendar is Empty");
            emptygpa.setText("Gpa is Empty");
        }
        else if(name.getText().trim().isEmpty())          
            emptyname.setText("Name is Empty");
        else if (level.getText().trim().isEmpty())
            emptylevel.setText("Level is Empty");
        else if (!(male.isSelected()) &&!(female.isSelected()))
            emptygendar.setText("Gendar is Empty");
        else if(gpa.getText().trim().isEmpty())
            emptygpa.setText("Gpais Empty");

        else
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url ="jdbc:sqlserver://localhost:1433;databaseName=test;user=sa;password=01098581649rod";
            Connection con =DriverManager.getConnection(url);
            String query = "insert into stdinfo(username,name,stdlevel,gendar,gpa)values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1,user);
            pst.setString(2,name.getText());
            pst.setString(3,level.getText());
            if(male.isSelected())
                gendar="Male";
            else if(female.isSelected())
                gendar="Female";
            pst.setString(4,gendar);
            pst.setString(5, gpa.getText()); 
            if((Integer.parseInt(level.getText()))<=4 && (Integer.parseInt(level.getText()))>0 ){
                if((Double.parseDouble(gpa.getText()))<=4 && Double.parseDouble(gpa.getText())>=0){
                     if(Integer.parseInt(level.getText())==1 && Double.parseDouble(gpa.getText())>0){
                        JOptionPane.showMessageDialog(null, "You don't have a Previous GPA !\n  Now Your GPA is 0.0");
                        pst.setString(5,"0.0"); 
                     }
                    pst.executeUpdate();          
                    JOptionPane.showMessageDialog(null,"Registered Completed ");
                    String sql="Select * from usercourses where username=?";
                    PreparedStatement pst1=con.prepareStatement(sql);               
                    pst1.setString(1,user);
                    ResultSet rs1=pst1.executeQuery();

                    if(!rs1.next())
                    {   
                        information_stusents display=new information_stusents();
                        display.setUP(user);
                        display.setVisible(true);
                        setVisible(false);
                    }
                    else {
                    modifiy show = new modifiy();
                    show.setUP(user);
                    show.setVisible(true);
                    setVisible(false);
                   }
                }
                else 
                    JOptionPane.showMessageDialog(null,"Invalid Gpa");

            }
            else {
                JOptionPane.showMessageDialog(null,"Invalid Level");
            }
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
    emptyname.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyReleased

    private void levelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_levelKeyReleased
    emptylevel.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_levelKeyReleased

    private void gpaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gpaKeyReleased
        emptygpa.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_gpaKeyReleased

    private void maleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maleKeyReleased
    emptygendar.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_maleKeyReleased

    private void femaleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_femaleKeyReleased
        emptygendar.setText("");        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_I_S_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_I_S_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_I_S_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_I_S_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_I_S_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel emptygendar;
    private javax.swing.JLabel emptygpa;
    private javax.swing.JLabel emptylevel;
    private javax.swing.JLabel emptyname;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField gpa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField level;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables

}
